### ISSUE TITLE
Larion crashes when I click "singleplayer" on the main menu.

### ISSUE THREAD

**Issue by AdamEternal** [ViciousBadger/larion-world-generation#2]
Larion crashes when I click "singleplayer" on the main menu.

Crash log:
https://pastebin.com/raw/QiEG5NgC

- Minecraft version: 1.20.1
- Fabric version: 0.16.2
- Fabric API version: 0.92.2
- More Density Functions version: 1.0.0
- Larion version: 1.0.0

**Comment by ViciousBadger** [comment]
Hi, unfortunately there are no revealing details in your crash log, so I cannot know for sure what caused the crash. There is likely some text above the ---- Minecraft Crash Report ---- part of your log that is more useful.

Anyway, More Density Functions used to have an issue with its versioning so every version from 1.0.0 to 1.0.4 were labeled as 1.0.0... this has been fixed with 1.0.5 so with the next release of Larion it'll bee easier..

The correct version of More Density Functions is 1.0.4, downloaded here: https://modrinth.com/mod/more-density-functions/version/tXb7qFTH
Older versions won't work due to breaking changes.
Try downloading this exact version and retrying.
