### ISSUE TITLE
Terrain Gen is all Windswept, no Flat Areas at All.

### ISSUE THREAD

**Issue by SongOfTheSky** [ViciousBadger/larion-world-generation#5]
After exploring around a bit in creative, I noticed that there is hardly any flat ground...it seems like everything is windswept, which makes exploring in survival rather difficult and frustrating, not to mention very difficult to build a base, unless you want to build your house into a cliff...

Is there no config file to change how the world generates? May you please add one?

The picture below is an orchard biome, which is normally supposed to be decently flat, with just a few small hills. But it generated windswept, with these weird flat squares...

![2024-10-19_19 37 29](https://github.com/user-attachments/assets/166f1639-1ef7-4373-8bbe-278d95d4f20b)

**Comment by ViciousBadger** [comment]
I've never seen square terrain like this. What other world gen mods are you using?
There should be flat ground, especially near coastlines.
No, i cant just "add" a config file but you can modify everything yourself, Larion is 95% just a custom datapack within the .jar file.

**Comment by SongOfTheSky** [comment]
I am using Biomes O Plenty, Regions Unexplored, Nature's Spirit, Mystic's Biomes, and a bunch of structure mods. I did have Tectonic previously, but I disabled it when I tested it, cause I know they are incompatible, but I did realize after that the config file for Tectonic was still present...so maybe that was messing with it? I'll try deleting the config file and deleting the mod instead of just disabling it, and see if that helps :)

Oh ok! I'll try editing the .jar file :) thanks!

**Comment by ViciousBadger** [comment]
Thanks for the response. I was curious because some biome mods (namely Terralith) also modify terrain generation and may interfere with Larion. It doesn't seem like BoP or Nature's spirit do this. I don't think you should worry about Terralith if it's disabled :)

Since you are using 1.20.1 I would guess you are running v3.2 of Larion which at this point is quite outdated.

My theory so far is that the screenshot was taken in a "high weirdness/ridges" or "peak" area, they tend to cause mildly-windswept terrain. If you take a screenshot with the debug overlay (F3) visible I can see if I am correct.

In version 3.6 I changed how the weirdness/ridges noise works so that "peak" areas dont really generate except for in mountains, you can try it out on the same seed and see if it's different, although there are other terrain changes that might interfere.

**Comment by SongOfTheSky** [comment]
I was using version 3.6, and it was still doing it :/ I have no idea what mod is conflicting with it...

If I were to modify the .jar file, to decrease the windswept...ness (the weirdness/ridges?), making the terrain a lot smoother, with no windsweptness, how would I do that? like, what would I need to modify? Like what file, in which folder, and what values do I change, and what do I change them to?

(I have no idea how to edit datapacks even, other than you can change the .jar to .zip, then extract it, then edit the files, then re-zip it, and change the extention back to .jar, but besides that, I have no idea how "noise" works, or what to change the values to, or even which files to edit...)

**Comment by ViciousBadger** [comment]
It's a stupidly complex thing to understand.. however we can try a quick "hack" and see if it fixes your issue. This will make the "windswept" effect disappear ENTIRELY from all terrain tho. Create a new file within the larion zip, put it in `data/minecraft/worldgen/density_function/overworld/` and call it `factor.json`. Within the file simply write "6.3", nothing else, without the quotes. "Factor" controls the "windswept-ness" of terrain and this will force it to a high value always. Lower value = more messed up terrain. Try adjusting it until it's good

**Comment by ViciousBadger** [comment]
I just had a look at the mods you're using and I found something that could be the culprit, it seems "Cavernous" overwrites a VERY important file that Larion also overwrites, `noise_settings/overworld.json`, which can lead to all sorts of issues depending on which mod happens to load first! I'm gonna check myself to see if cavernous messes things up

**Comment by ViciousBadger** [comment]
Okay so Cavernous without a doubt messes up everything. Mountains are chopped off and biomes are completely messed up. I'm still not sure if it's the cause of the windswept stuff.

Without cavernous:

![no-cavermous](https://github.com/user-attachments/assets/864d4023-16f3-457b-a273-0afa20fadef1)

With cavernous:

![with-cavernous](https://github.com/user-attachments/assets/3bb0c689-e3ca-46de-93b8-ea38d9df77bb)

It's a bit hard to see due to the cherry grove deciding to exist but the terrain shapes are definitely different..

**Comment by SongOfTheSky** [comment]
oh ok! wow thank you so much for this fix! I will try removing Cavernous and adding that extra folder like you mentioned and see what happens :) 

Also, does that mean that I have to remove the Cavernous datapack entirely? or can I just edit the Cavernous datapack to fix it?

And if I have to delete Cavernous entirely, would other cave mods cause the same issue? like mods that change how caves generate? Or would I need to stray away from any mods that change how caves generate as well?

**Comment by SongOfTheSky** [comment]
also, is there an easy way to change the size of biomes? I was hoping to keep the Mushroom Island as one big island, instead of groups of small islands, because I am playing with a datapack that adds mushroom villages to the mushroom island, and now the mushroom island is too small for the village to spawn...

**Comment by ViciousBadger** [comment]
Oh man. When combining as many biome and worldgen mods as you do, it is near inevitable that some of them overwrite the behaviour of others, and in all cases you can technically merge everything, but it's tough, so I'll leave that up to you. Best advice I can give is to look for files with the same path, find the same file in vanilla minecraft (https://github.com/misode/mcmeta/tree/data) then look for differences in all three and try to comprehend them.. or do a three-way merge using some tool.

About mushroom islands, that one is much easier, in `data/larion/worldgen/density_function/overworld/continents.json` you can basically tweak the sizes of them by changing the second point in the spline, the one that says `location: 0.10` - increasing that number should resize them.

**Comment by SongOfTheSky** [comment]
ok I'll give that a shot :) Thanks so much!!
